using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Data.SqlClient;
using System.Data;
using System.Configuration;

namespace GaaTemplate2
{
    public partial class WebForm2 : System.Web.UI.Page
    {
        /*public string GetConnectionString()
        {
            //sets the connection string from your web config file "ConnString" is the name of your Connection String
            return System.Configuration.ConfigurationManager.ConnectionStrings["GAAFixturesConnectionString"].ConnectionString;
        }*/
        public string GetConnectionString()
        {
            //sets the connection string from your web config file "ConnString" is the name of your Connection String
            return System.Configuration.ConfigurationManager.ConnectionStrings["GAAFixturesConnectionString"].ConnectionString;
        }


        protected void Page_Load(object sender, EventArgs e)
        {
            //linkbtnfacebook.Attributes.Add("onclick", "popWin(); return false; ");
           // linkbtnTwitter.Attributes.Add("onclick", "popWin2(); return false; ");
            
            
            string userID = (string)(Session["SessionUser"]);
           
           if (userID != null)
           {
                HyperLink1.Text = string.Format("Hello {0}, Log Out?", userID);
                HyperLink1.Target = "SignUp.aspx";
           }

            DataClasses1DataContext dc = new DataClasses1DataContext(GetConnectionString());

            var query = from u in dc.UserTbls
                        where u.UserName == userID
                        select u.AdminCap;
                                   
             foreach (var item in query)
            {
                if (item == null)
                {
                    GridView1.AutoGenerateDeleteButton = false;
                    GridView1.AutoGenerateEditButton = false;
                }
                else if (item == 1)
                {
                    GridView1.AutoGenerateDeleteButton = true;
                    GridView1.AutoGenerateEditButton = true;
                }
                else if (item ==2)
                {
                    GridView1.AutoGenerateDeleteButton = false;
                    GridView1.AutoGenerateEditButton = false;
                }
                else if(item==3)
                {
                    GridView1.AutoGenerateDeleteButton = false;
                    GridView1.AutoGenerateEditButton = false;
                }                
            }

             //var results = from f in dc.FixturesMatchesTbl
             //             join Teams in dc.TeamTbls on f.Team1ID equals Teams.TeamID
             //             select new { Teams.TeamID };
                      

        //   GridView1.DataSource = results;
        // GridView1.DataBind();
         }


        protected void DropDownList1_SelectedIndexChanged(object sender, EventArgs e)
        {
            GridView1.DataBind();
            DropDownList1.AutoPostBack = true;            
                 
        }

        protected void GridView1_SelectedIndexChanged(object sender, EventArgs e)
        {
          //  int index = Convert.ToInt16(GridView1.SelectedDataKey.Value);
        }

        protected void Button1_Click(object sender, EventArgs e)
        {
            Session["SessionUser"] = null;
            Response.Redirect("index.aspx");           
        }

        
    }
}